// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from '/Users/tangjiahui/Desktop/tjh/tiger-ui/node_modules/.pnpm/@umijs+renderer-react@4.0.70_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
};
