// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {
    '404': { id: '404', path: '*', parentId: 'DocLayout' },
    'dumi-context-layout': { id: 'dumi-context-layout', path: '/', isLayout: true },
    DocLayout: { id: 'DocLayout', path: '/', parentId: 'dumi-context-layout', isLayout: true },
    DemoLayout: { id: 'DemoLayout', path: '/', parentId: 'dumi-context-layout', isLayout: true },
    'docs/components/configProvider': {
      path: 'components/config-provider',
      id: 'docs/components/configProvider',
      parentId: 'DocLayout',
    },
    'docs/components/Notification': {
      path: 'components/notification',
      id: 'docs/components/Notification',
      parentId: 'DocLayout',
    },
    'docs/components/inputnumber': {
      path: 'components/inputnumber',
      id: 'docs/components/inputnumber',
      parentId: 'DocLayout',
    },
    'docs/components/datePicker': {
      path: 'components/date-picker',
      id: 'docs/components/datePicker',
      parentId: 'DocLayout',
    },
    'docs/components/pagination': {
      path: 'components/pagination',
      id: 'docs/components/pagination',
      parentId: 'DocLayout',
    },
    'docs/components/timepicker': {
      path: 'components/timepicker',
      id: 'docs/components/timepicker',
      parentId: 'DocLayout',
    },
    'docs/components/carousel': {
      path: 'components/carousel',
      id: 'docs/components/carousel',
      parentId: 'DocLayout',
    },
    'docs/components/checkbox': {
      path: 'components/checkbox',
      id: 'docs/components/checkbox',
      parentId: 'DocLayout',
    },
    'docs/components/collapse': {
      path: 'components/collapse',
      id: 'docs/components/collapse',
      parentId: 'DocLayout',
    },
    'docs/components/counter': {
      path: 'components/counter',
      id: 'docs/components/counter',
      parentId: 'DocLayout',
    },
    'docs/components/message': {
      path: 'components/message',
      id: 'docs/components/message',
      parentId: 'DocLayout',
    },
    'docs/components/popover': {
      path: 'components/popover',
      id: 'docs/components/popover',
      parentId: 'DocLayout',
    },
    'docs/components/tooltip': {
      path: 'components/tooltip',
      id: 'docs/components/tooltip',
      parentId: 'DocLayout',
    },
    'docs/components/button': {
      path: 'components/button',
      id: 'docs/components/button',
      parentId: 'DocLayout',
    },
    'docs/components/dialog': {
      path: 'components/dialog',
      id: 'docs/components/dialog',
      parentId: 'DocLayout',
    },
    'docs/components/drawer': {
      path: 'components/drawer',
      id: 'docs/components/drawer',
      parentId: 'DocLayout',
    },
    'docs/components/select': {
      path: 'components/select',
      id: 'docs/components/select',
      parentId: 'DocLayout',
    },
    'docs/components/slider': {
      path: 'components/slider',
      id: 'docs/components/slider',
      parentId: 'DocLayout',
    },
    'docs/components/switch': {
      path: 'components/switch',
      id: 'docs/components/switch',
      parentId: 'DocLayout',
    },
    'docs/components/upload': {
      path: 'components/upload',
      id: 'docs/components/upload',
      parentId: 'DocLayout',
    },
    'docs/components/alert': {
      path: 'components/alert',
      id: 'docs/components/alert',
      parentId: 'DocLayout',
    },
    'docs/components/empty': {
      path: 'components/empty',
      id: 'docs/components/empty',
      parentId: 'DocLayout',
    },
    'docs/components/image': {
      path: 'components/image',
      id: 'docs/components/image',
      parentId: 'DocLayout',
    },
    'docs/components/input': {
      path: 'components/input',
      id: 'docs/components/input',
      parentId: 'DocLayout',
    },
    'docs/components/radio': {
      path: 'components/radio',
      id: 'docs/components/radio',
      parentId: 'DocLayout',
    },
    'docs/components/space': {
      path: 'components/space',
      id: 'docs/components/space',
      parentId: 'DocLayout',
    },
    'docs/components/table': {
      path: 'components/table',
      id: 'docs/components/table',
      parentId: 'DocLayout',
    },
    'docs/components/tabs': {
      path: 'components/tabs',
      id: 'docs/components/tabs',
      parentId: 'DocLayout',
    },
    'docs/components/tree': {
      path: 'components/tree',
      id: 'docs/components/tree',
      parentId: 'DocLayout',
    },
    'docs/components/tag': {
      path: 'components/tag',
      id: 'docs/components/tag',
      parentId: 'DocLayout',
    },
    'docs/index': { path: '', id: 'docs/index', parentId: 'DocLayout' },
    'demo-render': { id: 'demo-render', path: '~demos/:id', parentId: 'DemoLayout' },
  } as const;
  return {
    routes,
    routeComponents: {
      '404': React.lazy(
        () => import(/* webpackChunkName: "dumi__pages__404" */ '@/dumi__pages/404'),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__ContextWrapper" */ '@/dumi__theme/ContextWrapper'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__layouts__DocLayout" */ '@/dumi__theme/layouts/DocLayout'
          ),
      ),
      DemoLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__layouts__DemoLayout" */ '@/dumi__theme/layouts/DemoLayout'
          ),
      ),
      'docs/components/configProvider': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__configProvider.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/configProvider.md'
          ),
      ),
      'docs/components/Notification': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__Notification.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/Notification.md'
          ),
      ),
      'docs/components/inputnumber': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__inputnumber.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/inputnumber.md'
          ),
      ),
      'docs/components/datePicker': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__datePicker.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/datePicker.md'
          ),
      ),
      'docs/components/pagination': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__pagination.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/pagination.md'
          ),
      ),
      'docs/components/timepicker': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__timepicker.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/timepicker.md'
          ),
      ),
      'docs/components/carousel': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__carousel.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/carousel.md'
          ),
      ),
      'docs/components/checkbox': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__checkbox.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/checkbox.md'
          ),
      ),
      'docs/components/collapse': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__collapse.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/collapse.md'
          ),
      ),
      'docs/components/counter': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__counter.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/counter.md'
          ),
      ),
      'docs/components/message': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__message.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/message.md'
          ),
      ),
      'docs/components/popover': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__popover.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/popover.md'
          ),
      ),
      'docs/components/tooltip': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__tooltip.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/tooltip.md'
          ),
      ),
      'docs/components/button': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__button.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/button.md'
          ),
      ),
      'docs/components/dialog': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__dialog.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/dialog.md'
          ),
      ),
      'docs/components/drawer': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__drawer.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/drawer.md'
          ),
      ),
      'docs/components/select': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__select.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/select.md'
          ),
      ),
      'docs/components/slider': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__slider.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/slider.md'
          ),
      ),
      'docs/components/switch': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__switch.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/switch.md'
          ),
      ),
      'docs/components/upload': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__upload.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/upload.md'
          ),
      ),
      'docs/components/alert': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__alert.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/alert.md'
          ),
      ),
      'docs/components/empty': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__empty.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/empty.md'
          ),
      ),
      'docs/components/image': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__image.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/image.md'
          ),
      ),
      'docs/components/input': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__input.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/input.md'
          ),
      ),
      'docs/components/radio': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__radio.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/radio.md'
          ),
      ),
      'docs/components/space': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__space.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/space.md'
          ),
      ),
      'docs/components/table': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__table.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/table.md'
          ),
      ),
      'docs/components/tabs': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__tabs.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/tabs.md'
          ),
      ),
      'docs/components/tree': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__tree.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/tree.md'
          ),
      ),
      'docs/components/tag': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__tag.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/components/tag.md'
          ),
      ),
      'docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ '/Users/tangjiahui/Desktop/tjh/tiger-ui/docs/index.md'
          ),
      ),
      'demo-render': React.lazy(
        () => import(/* webpackChunkName: "dumi__pages__Demo" */ '@/dumi__pages/Demo'),
      ),
    },
  };
}
