// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/tangjiahui/Desktop/tjh/tiger-ui/node_modules/.pnpm/dumi@2.2.1_prettier@2.8.7/node_modules/dumi/theme-default/slots/Footer/index.js';
