// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/tangjiahui/Desktop/tjh/tiger-ui/node_modules/dumi-theme-lobehub/dist/slots/Toc/index.js';
