// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/tangjiahui/Desktop/tjh/tiger-ui/node_modules/.pnpm/dumi@2.2.12_t6c3fpy3nuj4hbdy7klujng5tu/node_modules/dumi/theme-default/builtins/Tree/index.js';
