name: build docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: copy codes
        uses: actions/checkout@v4

      - name: install pnpm@8.15.0
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: run build.
        run:
          pnpm install && pnpm docs:build

      - name: Deploy To GitHub Page.🚀
        uses: JamesIves/github-pages-deploy-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          folder: docs-dist

