name: build docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: copy codes
        uses: actions/checkout@v4

      - name: install pnpm@8.15.0
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: run build.
        run: pnpm install && pnpm docs:build

      - name: Deploy To GitHub Page.🚀
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-page
          build_dir: docs-dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
