name: build docs

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: copy codes
        uses: actions/checkout@v4

      - name: install pnpm@7.30.5
        uses: pnpm/action-setup@v4
        with:
          version: 7.30.5

      - name: Install Dependencies.
        run: pnpm install

      - name: Build Docs.
        run: pnpm docs:build-github

      - name: Deploy To GitHub Page.🚀
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-page
          build_dir: docs-dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
